//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.13 at 10:50:27 AM CDT 
//


package mx.com.vepormas.banca.notificaciones.bean;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import mx.com.vepormas.banca.lib.bean.Response;
import mx.com.vepormas.banca.notificaciones.endpoint.NotificationsEndpoint;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://vepormas.com.mx/banca/schemas/base}Response">
 *       &lt;sequence>
 *         &lt;element name="data" type="{http://vepormas.com.mx/banca/schemas/generanotificaciones}Notification" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "GetNotificationCatalogResponse", namespace=NotificationsEndpoint.SCHEMA_NAMESPACE_URI)
@XmlSeeAlso( value={ Notification.class })
public class GetNotificationCatalogResponse
    extends Response<List<Notification>>
{
	/**
	 * 
	 */
	private static final long serialVersionUID = -6484758130126285954L;
	@XmlElement( name="data", required=true , namespace=NotificationsEndpoint.SCHEMA_NAMESPACE_URI)
    protected List<Notification> data;

    /**
     * Gets the value of the data property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the data property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Notification }
     * 
     * 
     */
    public List<Notification> getData() {
        if (data == null) {
            data = new ArrayList<Notification>();
        }
        return this.data;
    }

	public void setData(List<Notification> data) {
		this.data = data;
	}

}
