//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.19 at 07:13:36 PM CDT 
//


package mx.com.vepormas.banca.notificaciones.bean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.com.vepormas.banca.schemas.generanotificaciones package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.com.vepormas.banca.schemas.generanotificaciones
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetNotificationCatalogRequest }
     * 
     */
    public GetNotificationCatalogRequest createGetNotificationCatalogRequest() {
        return new GetNotificationCatalogRequest();
    }

    /**
     * Create an instance of {@link CatNotificationInput }
     * 
     */
    public CatNotificationInput createCatNotificationInput() {
        return new CatNotificationInput();
    }

    /**
     * Create an instance of {@link SendCommentRequest }
     * 
     */
    public SendCommentRequest createSendCommentRequest() {
        return new SendCommentRequest();
    }

    /**
     * Create an instance of {@link SendCommentDataInput }
     * 
     */
    public SendCommentDataInput createSendCommentDataInput() {
        return new SendCommentDataInput();
    }

    /**
     * Create an instance of {@link GetUserInformationForNotificationResponse }
     * 
     */
    public GetUserInformationForNotificationResponse createGetUserInformationForNotificationResponse() {
        return new GetUserInformationForNotificationResponse();
    }

    /**
     * Create an instance of {@link UserInformationOutput }
     * 
     */
    public UserInformationOutput createUserInformationOutput() {
        return new UserInformationOutput();
    }

    /**
     * Create an instance of {@link SendNotificationRequest }
     * 
     */
    public SendNotificationRequest createSendNotificationRequest() {
        return new SendNotificationRequest();
    }

    /**
     * Create an instance of {@link SendNotificationInput }
     * 
     */
    public SendNotificationInput createSendNotificationInput() {
        return new SendNotificationInput();
    }

    /**
     * Create an instance of {@link ExecuteSendPendingMailRequest }
     * 
     */
    public ExecuteSendPendingMailRequest createExecuteSendPendingMailRequest() {
        return new ExecuteSendPendingMailRequest();
    }

    /**
     * Create an instance of {@link GetNotificationCatalogResponse }
     * 
     */
    public GetNotificationCatalogResponse createGetNotificationCatalogResponse() {
        return new GetNotificationCatalogResponse();
    }

    /**
     * Create an instance of {@link Notification }
     * 
     */
    public Notification createNotification() {
        return new Notification();
    }

    /**
     * Create an instance of {@link SendNotificationAndAttachmentsRequest }
     * 
     */
    public SendNotificationAndAttachmentsRequest createSendNotificationAndAttachmentsRequest() {
        return new SendNotificationAndAttachmentsRequest();
    }

    /**
     * Create an instance of {@link AttachmentsInput }
     * 
     */
    public AttachmentsInput createAttachmentsInput() {
        return new AttachmentsInput();
    }

    /**
     * Create an instance of {@link GetUserInformationForNotificationRequest }
     * 
     */
    public GetUserInformationForNotificationRequest createGetUserInformationForNotificationRequest() {
        return new GetUserInformationForNotificationRequest();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link ParametersInput }
     * 
     */
    public ParametersInput createParametersInput() {
        return new ParametersInput();
    }

    public SendSMSRequest createSendSMSRequest(){
    	return new SendSMSRequest();
    }
    
    public SendSMSInput createSendSMSInput(){
    	return new SendSMSInput();
    }
}
