//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.28 at 06:49:51 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://vepormas.com.mx/banca/schemas/generanotificaciones", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package mx.com.vepormas.banca.notificaciones.bean;
