//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.19 at 07:13:36 PM CDT 
//


package mx.com.vepormas.banca.notificaciones.bean;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.vepormas.banca.lib.bean.Request;
import mx.com.vepormas.banca.notificaciones.endpoint.NotificationsEndpoint;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://vepormas.com.mx/banca/schemas/base}Request">
 *       &lt;sequence>
 *         &lt;element name="data" type="{http://vepormas.com.mx/banca/schemas/generanotificaciones}SendNotificationInput"/>
 *         &lt;element name="attachments" type="{http://vepormas.com.mx/banca/schemas/generanotificaciones}AttachmentsInput" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "SendNotificationAndAttachmentsRequest")
@XmlSeeAlso( value={ AttachmentsInput.class })
public class SendNotificationAndAttachmentsRequest
    extends Request<SendNotificationInput>
{

	private static final long serialVersionUID = 277574806219400699L;
	@XmlElement( name="data", required=true, namespace=NotificationsEndpoint.SCHEMA_NAMESPACE_URI )
	private SendNotificationInput data;
	@XmlElement( name="attachments", required=true, namespace=NotificationsEndpoint.SCHEMA_NAMESPACE_URI )
    protected List<AttachmentsInput> attachments;

  
    /**
     * Gets the value of the attachments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttachmentsInput }
     * 
     * 
     */
    public List<AttachmentsInput> getAttachments() {
        if (attachments == null) {
            attachments = new ArrayList<AttachmentsInput>();
        }
        return this.attachments;
    }


	public SendNotificationInput getData() {
		return data;
	}


	public void setData(SendNotificationInput data) {
		this.data = data;
	}

}
