//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.05 at 10:21:28 AM CDT 
//


package mx.com.vepormas.banca.notificaciones.wscli.user.information.ws_vpm_email_tel;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import mx.com.vepormas.banca.notificaciones.wscli.user.information.vpmemailtelnotif.VPMEMAILTELNOTIFType;


/**
 * <p>Java class for ConsultaemailynumtelResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConsultaemailynumtelResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Status" type="{http://temenos.com/WS.VPM.EMAIL.TEL.NOTIF}Status" minOccurs="0"/>
 *         &lt;element name="VPMEMAILTELNOTIFType" type="{http://temenos.com/VPMEMAILTELNOTIF}VPMEMAILTELNOTIFType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConsultaemailynumtelResponse", propOrder = {
    "status",
    "vpmemailtelnotifType"
})
public class ConsultaemailynumtelResponse {

    @XmlElement(name = "Status")
    protected Status status;
    @XmlElement(name = "VPMEMAILTELNOTIFType")
    protected List<VPMEMAILTELNOTIFType> vpmemailtelnotifType;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the vpmemailtelnotifType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vpmemailtelnotifType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVPMEMAILTELNOTIFType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VPMEMAILTELNOTIFType }
     * 
     * 
     */
    public List<VPMEMAILTELNOTIFType> getVPMEMAILTELNOTIFType() {
        if (vpmemailtelnotifType == null) {
            vpmemailtelnotifType = new ArrayList<VPMEMAILTELNOTIFType>();
        }
        return this.vpmemailtelnotifType;
    }

}
