//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.05 at 10:21:28 AM CDT 
//


package mx.com.vepormas.banca.notificaciones.wscli.user.information.ws_vpm_email_tel;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import mx.com.vepormas.banca.notificaciones.wscli.user.information.wseauthtoken.WSEAUTHTOKENType;



/**
 * <p>Java class for informaciIondeltokenResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="informaciIondeltokenResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Status" type="{http://temenos.com/WS.VPM.EMAIL.TEL.NOTIF}Status" minOccurs="0"/>
 *         &lt;element name="WSEAUTHTOKENType" type="{http://temenos.com/WSEAUTHTOKEN}WSEAUTHTOKENType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "informaciIondeltokenResponse", propOrder = {
    "status",
    "wseauthtokenType"
})
public class InformaciIondeltokenResponse {

    @XmlElement(name = "Status")
    protected Status status;
    @XmlElement(name = "WSEAUTHTOKENType")
    protected List<WSEAUTHTOKENType> wseauthtokenType;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the wseauthtokenType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wseauthtokenType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWSEAUTHTOKENType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WSEAUTHTOKENType }
     * 
     * 
     */
    public List<WSEAUTHTOKENType> getWSEAUTHTOKENType() {
        if (wseauthtokenType == null) {
            wseauthtokenType = new ArrayList<WSEAUTHTOKENType>();
        }
        return this.wseauthtokenType;
    }

}
