//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.05 at 10:21:28 AM CDT 
//


package mx.com.vepormas.banca.notificaciones.wscli.user.information.ws_vpm_email_tel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.temenos.ws_vpm_email_tel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Consultaemailynumtel_QNAME = new QName("http://temenos.com/WS.VPM.EMAIL.TEL.NOTIF", "Consultaemailynumtel");
    private final static QName _InformaciIondeltokenResponse_QNAME = new QName("http://temenos.com/WS.VPM.EMAIL.TEL.NOTIF", "informaciIondeltokenResponse");
    private final static QName _InformaciIondeltoken_QNAME = new QName("http://temenos.com/WS.VPM.EMAIL.TEL.NOTIF", "informaciIondeltoken");
    private final static QName _ConsultaemailynumtelResponse_QNAME = new QName("http://temenos.com/WS.VPM.EMAIL.TEL.NOTIF", "ConsultaemailynumtelResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.temenos.ws_vpm_email_tel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsultaemailynumtelResponse }
     * 
     */
    public ConsultaemailynumtelResponse createConsultaemailynumtelResponse() {
        return new ConsultaemailynumtelResponse();
    }

    /**
     * Create an instance of {@link InformaciIondeltoken }
     * 
     */
    public InformaciIondeltoken createInformaciIondeltoken() {
        return new InformaciIondeltoken();
    }

    /**
     * Create an instance of {@link InformaciIondeltokenResponse }
     * 
     */
    public InformaciIondeltokenResponse createInformaciIondeltokenResponse() {
        return new InformaciIondeltokenResponse();
    }

    /**
     * Create an instance of {@link Consultaemailynumtel }
     * 
     */
    public Consultaemailynumtel createConsultaemailynumtel() {
        return new Consultaemailynumtel();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link WebRequestCommon }
     * 
     */
    public WebRequestCommon createWebRequestCommon() {
        return new WebRequestCommon();
    }

    /**
     * Create an instance of {@link EnquiryInputCollection }
     * 
     */
    public EnquiryInputCollection createEnquiryInputCollection() {
        return new EnquiryInputCollection();
    }

    /**
     * Create an instance of {@link EnquiryInput }
     * 
     */
    public EnquiryInput createEnquiryInput() {
        return new EnquiryInput();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Consultaemailynumtel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://temenos.com/WS.VPM.EMAIL.TEL.NOTIF", name = "Consultaemailynumtel")
    public JAXBElement<Consultaemailynumtel> createConsultaemailynumtel(Consultaemailynumtel value) {
        return new JAXBElement<Consultaemailynumtel>(_Consultaemailynumtel_QNAME, Consultaemailynumtel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformaciIondeltokenResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://temenos.com/WS.VPM.EMAIL.TEL.NOTIF", name = "informaciIondeltokenResponse")
    public JAXBElement<InformaciIondeltokenResponse> createInformaciIondeltokenResponse(InformaciIondeltokenResponse value) {
        return new JAXBElement<InformaciIondeltokenResponse>(_InformaciIondeltokenResponse_QNAME, InformaciIondeltokenResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformaciIondeltoken }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://temenos.com/WS.VPM.EMAIL.TEL.NOTIF", name = "informaciIondeltoken")
    public JAXBElement<InformaciIondeltoken> createInformaciIondeltoken(InformaciIondeltoken value) {
        return new JAXBElement<InformaciIondeltoken>(_InformaciIondeltoken_QNAME, InformaciIondeltoken.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultaemailynumtelResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://temenos.com/WS.VPM.EMAIL.TEL.NOTIF", name = "ConsultaemailynumtelResponse")
    public JAXBElement<ConsultaemailynumtelResponse> createConsultaemailynumtelResponse(ConsultaemailynumtelResponse value) {
        return new JAXBElement<ConsultaemailynumtelResponse>(_ConsultaemailynumtelResponse_QNAME, ConsultaemailynumtelResponse.class, null, value);
    }

}
