//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.05 at 10:21:28 AM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://temenos.com/WS.VPM.EMAIL.TEL.NOTIF")
package mx.com.vepormas.banca.notificaciones.wscli.user.information.ws_vpm_email_tel;
