//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.05 at 10:21:28 AM CDT 
//


package mx.com.vepormas.banca.notificaciones.wscli.user.information.wseauthtoken;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.temenos.wseauthtoken package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WSEAUTHTOKENTypeGWSEAUTHTOKENDetailTypeMWSEAUTHTOKENDetailTypeTOKENSERIE_QNAME = new QName("http://temenos.com/WSEAUTHTOKEN", "TOKENSERIE");
    private final static QName _WSEAUTHTOKENTypeGWSEAUTHTOKENDetailTypeMWSEAUTHTOKENDetailTypeTOKENNIP_QNAME = new QName("http://temenos.com/WSEAUTHTOKEN", "TOKENNIP");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.temenos.wseauthtoken
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WSEAUTHTOKENType }
     * 
     */
    public WSEAUTHTOKENType createWSEAUTHTOKENType() {
        return new WSEAUTHTOKENType();
    }

    /**
     * Create an instance of {@link WSEAUTHTOKENType.GWSEAUTHTOKENDetailType }
     * 
     */
    public WSEAUTHTOKENType.GWSEAUTHTOKENDetailType createWSEAUTHTOKENTypeGWSEAUTHTOKENDetailType() {
        return new WSEAUTHTOKENType.GWSEAUTHTOKENDetailType();
    }

    /**
     * Create an instance of {@link WSEAUTHTOKENType.GWSEAUTHTOKENDetailType.MWSEAUTHTOKENDetailType }
     * 
     */
    public WSEAUTHTOKENType.GWSEAUTHTOKENDetailType.MWSEAUTHTOKENDetailType createWSEAUTHTOKENTypeGWSEAUTHTOKENDetailTypeMWSEAUTHTOKENDetailType() {
        return new WSEAUTHTOKENType.GWSEAUTHTOKENDetailType.MWSEAUTHTOKENDetailType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://temenos.com/WSEAUTHTOKEN", name = "TOKENSERIE", scope = WSEAUTHTOKENType.GWSEAUTHTOKENDetailType.MWSEAUTHTOKENDetailType.class)
    public JAXBElement<String> createWSEAUTHTOKENTypeGWSEAUTHTOKENDetailTypeMWSEAUTHTOKENDetailTypeTOKENSERIE(String value) {
        return new JAXBElement<String>(_WSEAUTHTOKENTypeGWSEAUTHTOKENDetailTypeMWSEAUTHTOKENDetailTypeTOKENSERIE_QNAME, String.class, WSEAUTHTOKENType.GWSEAUTHTOKENDetailType.MWSEAUTHTOKENDetailType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://temenos.com/WSEAUTHTOKEN", name = "TOKENNIP", scope = WSEAUTHTOKENType.GWSEAUTHTOKENDetailType.MWSEAUTHTOKENDetailType.class)
    public JAXBElement<String> createWSEAUTHTOKENTypeGWSEAUTHTOKENDetailTypeMWSEAUTHTOKENDetailTypeTOKENNIP(String value) {
        return new JAXBElement<String>(_WSEAUTHTOKENTypeGWSEAUTHTOKENDetailTypeMWSEAUTHTOKENDetailTypeTOKENNIP_QNAME, String.class, WSEAUTHTOKENType.GWSEAUTHTOKENDetailType.MWSEAUTHTOKENDetailType.class, value);
    }

}
