//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.05 at 10:21:28 AM CDT 
//


package mx.com.vepormas.banca.notificaciones.wscli.user.information.vpmemailtelnotif;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.temenos.vpmemailtelnotif package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VPMEMAILTELNOTIFTypeGVPMEMAILTELNOTIFDetailTypeMVPMEMAILTELNOTIFDetailTypeEMAILUSER_QNAME = new QName("http://temenos.com/VPMEMAILTELNOTIF", "EMAILUSER");
    private final static QName _VPMEMAILTELNOTIFTypeGVPMEMAILTELNOTIFDetailTypeMVPMEMAILTELNOTIFDetailTypeCUSTOMERID_QNAME = new QName("http://temenos.com/VPMEMAILTELNOTIF", "CUSTOMERID");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.temenos.vpmemailtelnotif
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VPMEMAILTELNOTIFType }
     * 
     */
    public VPMEMAILTELNOTIFType createVPMEMAILTELNOTIFType() {
        return new VPMEMAILTELNOTIFType();
    }

    /**
     * Create an instance of {@link VPMEMAILTELNOTIFType.GVPMEMAILTELNOTIFDetailType }
     * 
     */
    public VPMEMAILTELNOTIFType.GVPMEMAILTELNOTIFDetailType createVPMEMAILTELNOTIFTypeGVPMEMAILTELNOTIFDetailType() {
        return new VPMEMAILTELNOTIFType.GVPMEMAILTELNOTIFDetailType();
    }

    /**
     * Create an instance of {@link VPMEMAILTELNOTIFType.GVPMEMAILTELNOTIFDetailType.MVPMEMAILTELNOTIFDetailType }
     * 
     */
    public VPMEMAILTELNOTIFType.GVPMEMAILTELNOTIFDetailType.MVPMEMAILTELNOTIFDetailType createVPMEMAILTELNOTIFTypeGVPMEMAILTELNOTIFDetailTypeMVPMEMAILTELNOTIFDetailType() {
        return new VPMEMAILTELNOTIFType.GVPMEMAILTELNOTIFDetailType.MVPMEMAILTELNOTIFDetailType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://temenos.com/VPMEMAILTELNOTIF", name = "EMAILUSER", scope = VPMEMAILTELNOTIFType.GVPMEMAILTELNOTIFDetailType.MVPMEMAILTELNOTIFDetailType.class)
    public JAXBElement<String> createVPMEMAILTELNOTIFTypeGVPMEMAILTELNOTIFDetailTypeMVPMEMAILTELNOTIFDetailTypeEMAILUSER(String value) {
        return new JAXBElement<String>(_VPMEMAILTELNOTIFTypeGVPMEMAILTELNOTIFDetailTypeMVPMEMAILTELNOTIFDetailTypeEMAILUSER_QNAME, String.class, VPMEMAILTELNOTIFType.GVPMEMAILTELNOTIFDetailType.MVPMEMAILTELNOTIFDetailType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://temenos.com/VPMEMAILTELNOTIF", name = "CUSTOMERID", scope = VPMEMAILTELNOTIFType.GVPMEMAILTELNOTIFDetailType.MVPMEMAILTELNOTIFDetailType.class)
    public JAXBElement<String> createVPMEMAILTELNOTIFTypeGVPMEMAILTELNOTIFDetailTypeMVPMEMAILTELNOTIFDetailTypeCUSTOMERID(String value) {
        return new JAXBElement<String>(_VPMEMAILTELNOTIFTypeGVPMEMAILTELNOTIFDetailTypeMVPMEMAILTELNOTIFDetailTypeCUSTOMERID_QNAME, String.class, VPMEMAILTELNOTIFType.GVPMEMAILTELNOTIFDetailType.MVPMEMAILTELNOTIFDetailType.class, value);
    }

}
