//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.05 at 10:21:28 AM CDT 
//


package mx.com.vepormas.banca.notificaciones.wscli.user.information.vpmemailtelnotif;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VPMEMAILTELNOTIFType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VPMEMAILTELNOTIFType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gVPMEMAILTELNOTIFDetailType" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="mVPMEMAILTELNOTIFDetailType" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="EMAILUSER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="CUSTOMERID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="m" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="g" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VPMEMAILTELNOTIFType", propOrder = {
    "gvpmemailtelnotifDetailType"
})
public class VPMEMAILTELNOTIFType {

    @XmlElement(name = "gVPMEMAILTELNOTIFDetailType")
    protected VPMEMAILTELNOTIFType.GVPMEMAILTELNOTIFDetailType gvpmemailtelnotifDetailType;

    /**
     * Gets the value of the gvpmemailtelnotifDetailType property.
     * 
     * @return
     *     possible object is
     *     {@link VPMEMAILTELNOTIFType.GVPMEMAILTELNOTIFDetailType }
     *     
     */
    public VPMEMAILTELNOTIFType.GVPMEMAILTELNOTIFDetailType getGVPMEMAILTELNOTIFDetailType() {
        return gvpmemailtelnotifDetailType;
    }

    /**
     * Sets the value of the gvpmemailtelnotifDetailType property.
     * 
     * @param value
     *     allowed object is
     *     {@link VPMEMAILTELNOTIFType.GVPMEMAILTELNOTIFDetailType }
     *     
     */
    public void setGVPMEMAILTELNOTIFDetailType(VPMEMAILTELNOTIFType.GVPMEMAILTELNOTIFDetailType value) {
        this.gvpmemailtelnotifDetailType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="mVPMEMAILTELNOTIFDetailType" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="EMAILUSER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="CUSTOMERID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="m" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="g" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mvpmemailtelnotifDetailType"
    })
    public static class GVPMEMAILTELNOTIFDetailType {

        @XmlElement(name = "mVPMEMAILTELNOTIFDetailType")
        protected List<VPMEMAILTELNOTIFType.GVPMEMAILTELNOTIFDetailType.MVPMEMAILTELNOTIFDetailType> mvpmemailtelnotifDetailType;
        @XmlAttribute(name = "g")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger g;

        /**
         * Gets the value of the mvpmemailtelnotifDetailType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the mvpmemailtelnotifDetailType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMVPMEMAILTELNOTIFDetailType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link VPMEMAILTELNOTIFType.GVPMEMAILTELNOTIFDetailType.MVPMEMAILTELNOTIFDetailType }
         * 
         * 
         */
        public List<VPMEMAILTELNOTIFType.GVPMEMAILTELNOTIFDetailType.MVPMEMAILTELNOTIFDetailType> getMVPMEMAILTELNOTIFDetailType() {
            if (mvpmemailtelnotifDetailType == null) {
                mvpmemailtelnotifDetailType = new ArrayList<VPMEMAILTELNOTIFType.GVPMEMAILTELNOTIFDetailType.MVPMEMAILTELNOTIFDetailType>();
            }
            return this.mvpmemailtelnotifDetailType;
        }

        /**
         * Gets the value of the g property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getG() {
            return g;
        }

        /**
         * Sets the value of the g property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setG(BigInteger value) {
            this.g = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="EMAILUSER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="CUSTOMERID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="m" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "emailuser",
            "customerid"
        })
        public static class MVPMEMAILTELNOTIFDetailType {

            @XmlElementRef(name = "EMAILUSER", namespace = "http://temenos.com/VPMEMAILTELNOTIF", type = JAXBElement.class)
            protected JAXBElement<String> emailuser;
            @XmlElementRef(name = "CUSTOMERID", namespace = "http://temenos.com/VPMEMAILTELNOTIF", type = JAXBElement.class)
            protected JAXBElement<String> customerid;
            @XmlAttribute(name = "m")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger m;

            /**
             * Gets the value of the emailuser property.
             * 
             * @return
             *     possible object is
             *     {@link JAXBElement }{@code <}{@link String }{@code >}
             *     
             */
            public JAXBElement<String> getEMAILUSER() {
                return emailuser;
            }

            /**
             * Sets the value of the emailuser property.
             * 
             * @param value
             *     allowed object is
             *     {@link JAXBElement }{@code <}{@link String }{@code >}
             *     
             */
            public void setEMAILUSER(JAXBElement<String> value) {
                this.emailuser = value;
            }

            /**
             * Gets the value of the customerid property.
             * 
             * @return
             *     possible object is
             *     {@link JAXBElement }{@code <}{@link String }{@code >}
             *     
             */
            public JAXBElement<String> getCUSTOMERID() {
                return customerid;
            }

            /**
             * Sets the value of the customerid property.
             * 
             * @param value
             *     allowed object is
             *     {@link JAXBElement }{@code <}{@link String }{@code >}
             *     
             */
            public void setCUSTOMERID(JAXBElement<String> value) {
                this.customerid = value;
            }

            /**
             * Gets the value of the m property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getM() {
                return m;
            }

            /**
             * Sets the value of the m property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setM(BigInteger value) {
                this.m = value;
            }

        }

    }

}
